### ISSUE TITLE
KeePass 2.38 will fail with HideExpired plugin

### ISSUE THREAD

**Issue by michalzobec** [alexjustus/KeePass-HideExpired#1]
Hello, I will try your plugin HideExpired in last version with actual version of KeePass 2.38, but KeePass still fail. After I delete your plugin file HideExpired.dll, KeePass correctly running.

**Comment by alexjustus** [comment]
@michalzobec v2.0.0 of the plugin has been released which adds compatibility for the latest version of KeePass. You can download it here:
https://github.com/alexjustus/KeePass-HideExpired/releases/tag/v2.0.0

Thanks for the feedback!

**Comment by michalzobec** [comment]
@alexjustus thank you very much, I will test now :)
